FROM eclipse-temurin:21-jdk-jammy AS builder

WORKDIR /app

COPY mvnw ./
COPY .mvn/ ./.mvn/
RUN ./mvnw --version

COPY pom.xml ./
RUN ./mvnw -B dependency:go-offline

COPY src ./src
RUN ./mvnw -B -DskipTests package

FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar
COPY psicologiaaplicada-495911-e202675ec73d.json /app/

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
