server:
  servlet:
    context-path: /api

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/psicologia_aplicada
    username: root
    password: root
